### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/vertical-association#19]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] membership_extension - By @chienandalu - #35 
- [x] membership_initial_fee - By @chienandalu - #31 
- [x] membership_prorrate - By @chienandalu - #30 
- [x] membership_variable_period - By @chienandalu - #32 
- [x] membership_prorrate_variable_period - By @chienandalu - #34

**Comment by vonpupp** [comment]
Hello Pedro,

I don't know if this is the proper channel for this, if not I apologize. I am looking forward to be able to implement credit card/paypal recurrent donations for an NGO and I thought that this module might suit that scenario. I have never migrated a module, in fact I am quite newbie to Odoo, but if it would be possible to help the NGO to receive these recurrent donations I am willing to try to migrate it. #24 seems to have started the process, but I don't know if it will conclude.

Do you have any advice for the migration process?

Thank you very much.

**Comment by pedrobaeza** [comment]
As you don't have too much experience, just wait for the completion of the migration.

**Comment by pedrobaeza** [comment]
All modules migrated.
