### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/vertical-association#40]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] contract_membership_delegated_partner - By @chienandalu - #61
- [x] membership_delegated_partner - By @chienandalu - #46 
- [x] membership_extension - By @chienandalu - #42 
- [x] membership_initial_fee - By @chienandalu - #43 
- [x] membership_prorrate > membership_prorate - By @chienandalu - #41 
- [x] membership_prorrate_variable_period - By @chienandalu - #59 
- [x] membership_variable_period - By @chienandalu - #44 
- [x] membership_withdrawal - By @chienandalu - #58

**Comment by pedrobaeza** [comment]
Everything migrated.
