### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/vertical-association#8]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] membership_prorrate
- [ ] membership_initial_fee
- [x] membership_variable_period - By @leemannd - #18
- [ ] membership_prorrate_variable_period
- [ ] website_membership_contact_visibility - By @mikevhe18 - #20

**Comment by leemannd** [comment]
@pedrobaeza We are looking to eventually port membership_variable_period in https://github.com/OCA/vertical-association/pull/18 . For the moment we are doing functional tests.

**Comment by pedrobaeza** [comment]
Thanks, written in the initial comment

**Comment by jayo2005** [comment]
Will this module be migrated to V9 or V10

**Comment by pedrobaeza** [comment]
No contributions for now...

**Comment by pedrobaeza** [comment]
Closing as no expected to be migrated to this version being on v9/v10.
